In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [3]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([2,4,5,6,7,8,0])

array([2, 4, 5, 6, 7, 8, 0])

In [5]:
np.array([1,2,3,4,5,"hasmukh",5+8j])

array(['1', '2', '3', '4', '5', 'hasmukh', '(5+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4.5,6.0]) #upcast automatically   

array([1. , 2. , 3. , 4.5, 6. ])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [8]:
np.array([[1,3],[3,4],[6,7,8]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [9]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]]) 

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [10]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [11]:
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [12]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [14]:
arr=np.array([(1,2),(3,4)],dtype=[("a","<i2"),('b','<i8')])


In [15]:
type(arr[0][0])

numpy.int16

In [16]:
type(arr[0][1])

numpy.int64

In [17]:
arr=np.array([(1,2),(3,4)])

In [18]:
arr

array([[1, 2],
       [3, 4]])

In [19]:
type(arr[0][1])

numpy.int64

In [20]:
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [21]:
l=[4,3,5,65,6,6]

In [22]:
np.array(l)

array([ 4,  3,  5, 65,  6,  6])

In [23]:
np.asarray(l)

array([ 4,  3,  5, 65,  6,  6])

In [24]:
np.asanyarray(l)

array([ 4,  3,  5, 65,  6,  6])

In [25]:
mat=np.mat(arr)

In [26]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [27]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [28]:
issubclass(np.matrix,np.ndarray) #matrix is a subclass of array

True

In [29]:
issubclass(np.ndarray,np.matrix)
#array is not a subclass of matrix


False

In [30]:
arr

array([[1, 2],
       [3, 4]])

In [31]:
a=arr

In [32]:
b=np.copy(a)

In [33]:
b

array([[1, 2],
       [3, 4]])

In [34]:
arr[0][0]=67

In [35]:
arr

array([[67,  2],
       [ 3,  4]])

In [36]:
a


array([[67,  2],
       [ 3,  4]])

In [37]:
b

array([[1, 2],
       [3, 4]])

In [38]:
arr[0:10]

array([[67,  2],
       [ 3,  4]])

In [39]:
arr[-1]

array([3, 4])

In [40]:
for i in arr:
  print(i)

[67  2]
[3 4]


In [41]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [42]:
type(np.fromfunction(lambda i,j:i==j,(4,4)))

numpy.ndarray

In [43]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
np.fromfunction(lambda i,j:i/j,(3,3))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [45]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [46]:
(i*i for i in range(5)) #generator


<generator object <genexpr> at 0x7ff24c9a71d0>

In [47]:
def test(x):
  yield x

In [48]:
test(5)

<generator object test at 0x7ff24c9a74d0>

In [49]:
gen=(i*i for i in range(5))

In [50]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [51]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [52]:
np.fromstring('1,3,4,5,5',sep=',',dtype=int)

array([1, 3, 4, 5, 5])

In [53]:
np.fromstring("456 5656 4545 443",sep=" ",dtype=complex
              )

array([ 456.+0.j, 5656.+0.j, 4545.+0.j,  443.+0.j])

In [54]:
l=[3,4,5,6,67]

In [55]:
arr=np.array(l)

In [56]:
arr1=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [57]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [58]:
type(arr)

numpy.ndarray

In [59]:
type(arr1)

numpy.ndarray

In [60]:
arr1.ndim

2

In [61]:
arr1.size

12

In [62]:
arr1.shape

(3, 4)

In [63]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [64]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [65]:
arr2.size

16

In [66]:
arr2.ndim

3

In [67]:
arr2.shape

(2, 2, 4)

In [68]:
arr4=np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [69]:
arr4


array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [70]:
arr4.shape

(1, 4, 2, 4)

In [71]:
arr4.ndim

4

In [72]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [73]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [74]:
np.arange(6.6,10,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6, 9.9])

In [75]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros((2,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
np.ones(4)

array([1., 1., 1., 1.])

In [80]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.ones((2,3))+6

array([[7., 7., 7.],
       [7., 7., 7.]])

In [82]:
np.empty((2,4))

array([[1.39941525e-316, 2.35541533e-312, 2.14321575e-312,
        8.48798317e-313],
       [1.06099790e-312, 1.08221785e-312, 8.70018274e-313,
        6.46048250e-313]])

In [83]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
d=np.linspace(4,7,40)

In [85]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [86]:
d.ndim

1

In [87]:
d.shape

(40,)

In [88]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [90]:
np.linspace(2,4,4,endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [93]:
# np.linspace(2,4,4,endpoint=True,axis=1)


In [96]:
np.linspace([2,4],4,endpoint=False,axis=1)


array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [98]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [99]:
np.random.rand(3)

array([0.5828338 , 0.17551266, 0.45572607])

In [100]:
np.random.rand(5)


array([0.08564731, 0.31268832, 0.11574308, 0.53191104, 0.88509112])

In [105]:
np.random.randint(10)


5

In [106]:
np.random.randn(5)


array([-1.43853503, -1.13451096,  0.77795416,  0.92162848, -0.8750823 ])

In [107]:
np.random.randint(5,10)

8

In [108]:
np.random.randint(5,10,(3,3))

array([[9, 5, 6],
       [5, 7, 7],
       [8, 7, 6]])

In [109]:
arr = np.random.randint(3,9,(3,3))

In [110]:
arr

array([[5, 4, 4],
       [8, 4, 5],
       [5, 3, 3]])

In [111]:
arr.reshape(1,9)

array([[5, 4, 4, 8, 4, 5, 5, 3, 3]])

In [112]:
arr.reshape(9,1)


array([[5],
       [4],
       [4],
       [8],
       [4],
       [5],
       [5],
       [3],
       [3]])

In [113]:
arr.reshape(1,1,9)

array([[[5, 4, 4, 8, 4, 5, 5, 3, 3]]])

In [114]:
arr.reshape(3,3,1)

array([[[5],
        [4],
        [4]],

       [[8],
        [4],
        [5]],

       [[5],
        [3],
        [3]]])

In [115]:
arr

array([[5, 4, 4],
       [8, 4, 5],
       [5, 3, 3]])

In [116]:
arr.max()

8

In [117]:
arr.min()

3

In [120]:
arr = np.random.randint(4,100,(5,5))

In [121]:
arr

array([[76, 55, 23, 58, 86],
       [54, 42, 40, 11, 45],
       [17, 66, 24, 21, 10],
       [89, 94, 76, 92, 10],
       [89, 90, 63,  9, 19]])

In [122]:
arr[3:,3:]

array([[92, 10],
       [ 9, 19]])

In [125]:
arr[:,[1,3]]

array([[55, 58],
       [42, 11],
       [66, 21],
       [94, 92],
       [90,  9]])

In [126]:
arr>True

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [127]:
arr[arr>10]

array([76, 55, 23, 58, 86, 54, 42, 40, 11, 45, 17, 66, 24, 21, 89, 94, 76,
       92, 89, 90, 63, 19])

In [128]:
arr1=np.random.randint(2,4,(3,3))

In [129]:
arr1

array([[3, 3, 2],
       [3, 3, 3],
       [2, 3, 2]])

In [130]:
arr2=np.random.randint(2,4,(3,3))

In [131]:
arr2


array([[3, 2, 2],
       [2, 3, 2],
       [3, 3, 2]])

In [133]:
arr1*arr2 #index multiplication

array([[9, 6, 4],
       [6, 9, 6],
       [6, 9, 4]])

In [135]:
arr1@arr2 #matrix multiplication

array([[21, 21, 16],
       [24, 24, 18],
       [18, 19, 14]])

In [136]:
arr/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [137]:
arr

array([[76, 55, 23, 58, 86],
       [54, 42, 40, 11, 45],
       [17, 66, 24, 21, 10],
       [89, 94, 76, 92, 10],
       [89, 90, 63,  9, 19]])

In [138]:
arr**2

array([[5776, 3025,  529, 3364, 7396],
       [2916, 1764, 1600,  121, 2025],
       [ 289, 4356,  576,  441,  100],
       [7921, 8836, 5776, 8464,  100],
       [7921, 8100, 3969,   81,  361]])

In [139]:
arr=np.zeros((3,4))

In [140]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
a=np.array([1,2,3,4])

In [142]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [144]:
arr +5 #broadcast

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [149]:
b=np.array([3,4,5])

b+4

array([7, 8, 9])

In [150]:
arr + b

ValueError: ignored

In [151]:
b.reshape(3,1)

array([[3],
       [4],
       [5]])

In [152]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
b.reshape(3,1) + arr

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [155]:
b

array([3, 4, 5])

In [156]:
b.T

array([3, 4, 5])

In [157]:
b=np.array([[5,6,7]])

In [158]:
b.T

array([[5],
       [6],
       [7]])

In [159]:
arr = np.random.rand(5,4)

In [161]:
arr

array([[0.23923591, 0.78375672, 0.87715968, 0.27500041],
       [0.49223291, 0.37163398, 0.43732771, 0.55938281],
       [0.51346542, 0.44993088, 0.29066214, 0.48954394],
       [0.84528254, 0.27696662, 0.90922695, 0.39336377],
       [0.54589797, 0.10470947, 0.71731805, 0.29819312]])

In [160]:
np.sqrt(arr)

array([[0.48911748, 0.88530036, 0.93656803, 0.52440481],
       [0.70159313, 0.60961789, 0.66130758, 0.74791899],
       [0.71656501, 0.67076887, 0.53913091, 0.69967417],
       [0.91939249, 0.52627618, 0.95353393, 0.62718719],
       [0.73884908, 0.32358843, 0.84694631, 0.54607061]])

In [162]:
np.log10(arr)

array([[-0.62117363, -0.10581872, -0.05692134, -0.56066666],
       [-0.30782935, -0.42988459, -0.359193  , -0.25229088],
       [-0.2894888 , -0.3468542 , -0.53661153, -0.31020832],
       [-0.0729981 , -0.55757258, -0.0413277 , -0.40520564],
       [-0.26288852, -0.98001403, -0.14428824, -0.52550239]])

In [163]:
np.log10(10)

1.0

In [164]:
arr1=np.random.randint(2,5,(5,5))
arr1

array([[4, 4, 4, 4, 3],
       [3, 2, 2, 2, 4],
       [4, 4, 4, 4, 2],
       [4, 4, 3, 4, 3],
       [4, 2, 3, 3, 2]])

In [165]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.47712125],
       [0.47712125, 0.30103   , 0.30103   , 0.30103   , 0.60205999],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.30103   ],
       [0.60205999, 0.60205999, 0.47712125, 0.60205999, 0.47712125],
       [0.60205999, 0.30103   , 0.47712125, 0.47712125, 0.30103   ]])

In [166]:
np.random.seed(13)

In [170]:
np.random.rand(2,4) #everytime you run this you get different answer

array([[0.03190367, 0.06508454, 0.629829  , 0.87381344],
       [0.00871573, 0.74657724, 0.81284117, 0.07571745]])

In [171]:
np.random.seed(13)
np.random.rand(2,4) #everytime you run this you get same answer


array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])