1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [2]:
# 1. Write a Python Program to Add Two Matrices?
import numpy as np
try:
    m1=np.matrix([[2,3,4],[5,6,7]])
    m2=np.matrix([[9,3,12],[12,34,45]])
    if m1.shape==m2.shape:
    
        print(m1+m2)
    else:
        print("Addition not possible")
    # print(m1)
    

except Exception as e:
    print("exception occured",str(e))

[[11  6 16]
 [17 40 52]]


In [3]:
# 2. Write a Python Program to Multiply Two Matrices?

import numpy as np
try:
    m1=np.matrix([[1,2,3]
                ])
    m2=np.matrix([[9],
                [12],[7]])


    m1_row=m1.shape[1]
    m2_column=m2.shape[0]

    if m1_row==m2_column:
        print(m1@m2)
    else:
        print("multiplication not possible")

    

except Exception as e:
    print("exception occured",str(e))

[[54]]


In [6]:
# 3. Write a Python Program to Transpose a Matrix?

try:
    m1=np.matrix([[1,2,3],[4,5,6]
                ])
    print(m1.T)
except Exception as e:
    print("exception occured",str(e))

[[1 4]
 [2 5]
 [3 6]]


In [17]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

try:
    words_num=int(input("how many numbers of words you want to sort "))
    i=0
    word_list=[]
    while i<words_num:
        wd=input("enter your word number {}".format(i))
        word_list.append(wd)
        i=i+1

    sorted_list=sorted(word_list)
    print("Sorted List =={}".format(sorted_list))

  
except Exception as e:
    print("exception occured",str(e))


Sorted List ==['dasd', 'sdasdd']


In [6]:
# 5. Write a Python Program to Remove Punctuation From a String?

import re
try:
    my_str = input("enter your string")
    out = re.sub(r'[^a-zA-Z0-9\s]', '', my_str)
    print(out)
except Exception as e:
    print("exception occured",str(e))



hsfdhs6asdasd7fsdf8f8sdf9fsdf
